"""Build a Cloudflare-friendly JS bundle from repo-managed profile markdown."""

import json
from datetime import UTC, datetime
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
PROFILES_ROOT = REPO_ROOT / "src" / "pipeidea" / "profiles"
OUTPUT_PATH = REPO_ROOT / "cloudflare" / "worker" / "src" / "generated" / "profiles.mjs"
SOUL_FILE_ORDER = [
    "identity.md",
    "taste.md",
    "ambition.md",
    "knowledge.md",
    "randomness.md",
    "techniques.md",
    "protocol.md",
    "dialogue.md",
    "output.md",
    "modes/bloom.md",
    "modes/collision.md",
    "modes/forage.md",
    "modes/revisit.md",
]


def collect_profiles() -> dict[str, dict[str, object]]:
    profiles: dict[str, dict[str, object]] = {}
    if not PROFILES_ROOT.exists():
        raise FileNotFoundError(f"Profile root not found: {PROFILES_ROOT}")

    for profile_dir in sorted(path for path in PROFILES_ROOT.iterdir() if path.is_dir()):
        files: dict[str, str] = {}
        for path in sorted(profile_dir.rglob("*.md")):
            relative = path.relative_to(profile_dir).as_posix()
            files[relative] = path.read_text(encoding="utf-8")

        profiles[profile_dir.name] = {
            "name": profile_dir.name,
            "files": files,
        }

    return profiles


def render_module(bundle: dict[str, object]) -> str:
    payload = json.dumps(bundle, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// Generated by scripts/build_profiles_bundle.py. Do not edit by hand.\n"
        f"export const PROFILE_BUNDLE = {payload};\n"
    )


def main() -> None:
    bundle = {
        "generated_at": datetime.now(UTC).isoformat(),
        "source_root": str(PROFILES_ROOT.relative_to(REPO_ROOT)),
        "default_profile": "default",
        "file_order": SOUL_FILE_ORDER,
        "profiles": collect_profiles(),
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render_module(bundle), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
